### ISSUE TITLE
Runs commands on refreshing of project

### ISSUE THREAD

**Issue by luke-barnett** [kmees/MSBuild.NodeTools#10]
I'm only expecting this to run during build but I'm noticing that my Visual Studio locks up for a bit every now and then as the project refreshes. I then started to notice that if I nuked my node_components folder it would appear again if I refreshed the project.

This should only happen during build/manual calling not when refreshing the project in some manner.

**Comment by kmees** [comment]
The targets are set to run on `PrepareForBuild` and it looks like VS occasionally triggers that by itself but I cannot really find any documentation about that. I might have to switch to `Build` but this has its own issues.

**Comment by luke-barnett** [comment]
There is the BeforeBuild as well right?

**Comment by kmees** [comment]
Fixed in [0.4.2]( https://github.com/kmees/MSBuild.NodeTools/commit/cf025050fdf86e6526c6873c5c939b299e258149)
