### ISSUE TITLE
Looking for grunt in AppData\Roaming\npm instead of in the local node_modules folder

### ISSUE THREAD

**Issue by janaagaard75** [kmees/MSBuild.NodeTools#20]
This line in my csproj file gives me a build error because It's looking for Grunt in the %USERPROFILE%\AppData\Roaming\npm folder. I am using MSBuild.Npm to make it install all necessary Node modules in a node_modules local to my Visual Studio project, so I don't need to have grunt installed globally.

    <Import Project="..\packages\MSBuild.Grunt.0.4.4\build\MSBuild.Grunt.props" Condition="Exists('..\packages\MSBuild.Grunt.0.4.4\build\MSBuild.Grunt.props')" />

I guess the line above doesn't take into account that I might be installing my packages locally.

**Comment by kmees** [comment]
You need to set the `LocalNodeModulePath` (see README) if you use a local gulp or grunt installation
