### ISSUE TITLE
Quotes around $(GruntBuildTask) limits additional options

### ISSUE THREAD

**Issue by JamesInDenver** [kmees/MSBuild.NodeTools#21]
In MSBuild.Grunt.targets the only available parameter is GruntBuildTask which has quotes around it.  Grunt treats multiple parameters surrounded by quotes as a single parameter and fails.  For example: "build --environment=test --force" is treated as a single parameter and grunt looks for a task called "build --environment=test --force" instead of treating it as multiple parameters.

**Comment by kmees** [comment]
I guess it's fine to remove them, I actually can't remember why i surrounded it in the first place. So i guess its fine to remove them.

**Comment by dtesta** [comment]
Just for history, the quotes were added in commit c58ea8670925486794cc0f7e0253997b48797b59 (I should have created and linked to an issue). @JamesInDenver's issue shows it was a poor "fix" on my part. I'm still using an older version, but I did a quick test with 0.5.1 and was not able to recreate the issue I was seeing in 0.4.2.
