### ISSUE TITLE
Gulp module not found unless Gulp is installed globally

### ISSUE THREAD

**Issue by geirsagberg** [kmees/MSBuild.NodeTools#22]
I want to be able to run gulp from local node_modules, so I don't have to install gulp globally on every build agent. Any tips?

**Comment by geirsagberg** [comment]
The error I get is: `Gulp module not found. Please install Gulp in the node module path 'C:\Users\MyUser\AppData\Roaming\npm`

**Comment by geirsagberg** [comment]
Nevermind, fixed it by adding:

    <LocalNodeModulePath>$(SolutionDir)node_modules/.bin</LocalNodeModulePath>

Feel free to close this :)

**Comment by bkraider** [comment]
Where did you add the <LocalNodeModulePath> to the visual studio solution file?

**Comment by geirsagberg** [comment]
@bkraider the line must be added to your web project's `.csproj`-file, not the solution file. To be honest, I do not remember any more details; it is almost three years ago, these days I use webpack instead of gulp :)
