### ISSUE TITLE
node_modules not included in site deploy

### ISSUE THREAD

**Issue by enoshixi** [kmees/MSBuild.NodeTools#7]
The npm install runs successfully during the build, however, when deploying the site the folder is not there.

What am I missing?

**Comment by kmees** [comment]
Why do you need the `node_modules` folder in your deployment? There should be only development dependencies in there.

**Comment by enoshixi** [comment]
We have some production dependencies.  Scripts that run on request.

**Comment by kmees** [comment]
My guess ist that you need to add the `node_modules` folder to your VS Project, but without any additional informations about your setup I cannot really help. 
Also, having node modules as a production dependecy is more of an edge case I guess.
