### ISSUE TITLE
Missing build folder for Node.0.2.0

### ISSUE THREAD

**Issue by eatlakson** [kmees/MSBuild.NodeTools#9]
When I install MSBuild.NodeTools via nuget package manger all seems fine, except for there is neither a builder folder nor its contents (MSBuild.Node.(props | targers)) for the MSBuild.Node.0.2.0 package. I was able to copy and paste the source from GitHub once I saw the errors and realized what happened, but thought you may want to investigate.

**Comment by kmees** [comment]
That was fixed in 0.2.1. It's an old version
